### ISSUE TITLE
Add support of PEP 518 to avoid issue with numpy during installation

### ISSUE THREAD

**Issue by savmickael** [fhs/pyhdf#37]
### What version of pyhdf, HDF4, and Python are you using?

pyhdf version: 0.10.1
HDF4 C library version: 4.2.10-3.2 
Python version: 2.7.12

### What operating system are you using?

Ubuntu 16.04, x64

### What did you do?

Run pip install pyhdf from an empty virtualenv or run pip install -r requirement.file with pyhdf and numpy inside.

### What did you expect to see?

Right installation

### What did you see instead?

Error because numpy is not previously installed or numpy not installed before pyhdf through the requirement file. Therefore I need to install manually numpy before.

The [PEP 518](https://www.python.org/dev/peps/pep-0518/) is now here to solve this type of issue by defined requirement for build system.

**Comment by NBrown140** [comment]
I've encountered the same problem.

**Comment by fhs** [comment]
Does PR #38 fix the issue?
