### ISSUE TITLE
The NPY_CHAR type_num is deprecated

### ISSUE THREAD

**Issue by zmoon** [fhs/pyhdf#52]
### What version of pyhdf, HDF4, and Python are you using?

pyhdf version: 0.10.3
HDF4 C library version: 4.2.15
Python version: 3.10.2
NumPy: 1.22.2

### What operating system are you using?

Windows

### The issue

There is a deprecation warning from numpy:

```
... site-packages\pyhdf\SD.py:1920: DeprecationWarning: The NPY_CHAR type_num is deprecated. Please port your code to use NPY_STRING instead.
    return _C._SDreaddata_0(self._id, data_type, start, count, stride)
```

I saw this message in another issue or two but didn't seem like there was specific one noting this deprecation.

**Comment by fhs** [comment]
Fixed in 2c5494910299ac2e31844cd718ce751a31d4f4cc
