### ISSUE TITLE
Build fails in Windows when using MinGW

### ISSUE THREAD

**Issue by juanangelacero** [fhs/pyhdf#9]
I am trying to install python-hdf4-0.9 with python 3.4  in windows 7 but I am not able. I would pleased if somebody could help me.

I try to follow the following instructions, but stay in step 4.
When I run 
python setup.py build -c mingw32 --hdf4 C:\HDF4
I get that  
```
d:\UTIL\python\3.4.1\python-hdf4-0.9>python setup.py build -c mingw32 --hdf4 C:\
HDF4
Using include_dirs =  ['C:\HDF4\42r3-win-vnet-enc\include']
Using library_dirs =  ['C:\HDF4\42r3-win-vnet-enc\dll', 'C:\HDF4\42r3-win-v
net-enc\lib', 'C:\HDF4\jpeg6-vnet\lib', 'C:\HDF4\szip21-vnet-enc\lib', 'C
:\HDF4\zlib123-vnet\lib']
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler opti
ons
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler opt
ions
running build_src
build_src
building extension "pyhdf._hdfext" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    platforms    = ["Windows", "Linux", "Solaris", "Mac OS-X", "Unix"],
  File "C:\Python34\lib\site-packages\numpy\distutils\core.py", line 169, in set
up
    return old_setup(**new_attr)
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\numpy\distutils\command\build.py", line 39
, in run
    old_build.run(self)
  File "C:\Python34\lib\distutils\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\numpy\distutils\command\build_ext.py", lin
e 94, in run
    force=self.force)
  File "C:\Python34\lib\site-packages\numpy\distutils\ccompiler.py", line 562, i
n new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Python34\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line
 57, in __init__
    verbose, dry_run, force)
  File "C:\Python34\lib\distutils\cygwinccompiler.py", line 126, in **init**
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()
```
I do not know if this type error has to be understood as failure.
I would be very please to receive help because this is getting me crazy

Thanks
## Quick install from Source for Windows Users

**Requirements**:
- `Python 2.5+ <http://www.python.org>`_
- `NumPy 1.0.4+  <http://www.scipy.org>`_
- `Mingw32 compiler <http://www.mingw.org>`_ or Visual Studio .NET 2003
1. Download the complete HDF4 binary package from the link given
   below.  These packages include all libraries needed to compile
   pyhdf. There are two binary packages to choose from depending on
   whether or not you want to compile pyhdf with SZIP encoding enabled
   or disabled.  There are different licensing implications for each
   choice (see `the HDF page
   <http://hdfgroup.com/doc_resource/SZIP/>`_ for more details on the
   licensing of SZIP).
   - `HDF4 with encoding enabled <http://pysclint.sourceforge.net/pyhdf/hdf4-all-enc.zip>`_
   - `HDF4 with encoding disabled <http://pysclint.sourceforge.net/pyhdf/hdf4-all-noenc.zip>`_
2. Unzip the selected package into a directory of your choice (e.g. C:\HDF4).  
3. Go to the `pyhdf` source directory.
4. Build the package in one of the two following ways:
   - Set the HDF4 environment variable to the directory where you unpacked the binary and (e.g. C:\HDF4). Then run the following::
   
   python setup.py build
   - Run `python setup.py build --hdf4 <directory of unzipped package>` where `<directory of unzipped package>` is the location where you unzipped the downloaded HDF4 binary (e.g. C:\HDF4).
   
   _NOTE_: If you are using the mingw32 compiler and are using the
   standard Python binary distribution, then you need to specify -c
   mingw32 on the command line as well.
5. Install `pyhdf` or build a binary distribution (bdist_msi,
   bdist_wininst, bdist_egg, etc.) then run one of the following commands::
   
   python setup.py install
   python setup.py bdist_msi
   python setup.py bdist_wininst
   python setup.py bdist_egg

**Comment by fhs** [comment]
This method of installing pyhdf is no longer supported (see https://github.com/fhs/pyhdf/commit/e548fc54beed817c2d5aefd1799028b3e1ad9e3c). The hdf4 binaries you are using are very outdated at this point, and it's questionable how compatible mingw is when building python extensions. I was able to build 32-bit pyhdf using mingw, but I am getting unresolved symbols when linking the 64-bit version. It's generally recommended to use Visual C++ when building python extensions because CPython is built using Visual C++: https://wiki.python.org/moin/WindowsCompilers

I recommend you use conda to install pyhdf, now that conda builds of pyhdf are available for Windows.
